"""empty message

Revision ID: ef02a3d3d35a
Revises: d4ef3547a228
Create Date: 2021-05-13 17:27:08.582616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef02a3d3d35a'
down_revision = 'd4ef3547a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('continent', sa.String(length=80), nullable=True),
    sa.Column('date_range_start', sa.String(length=80), nullable=True),
    sa.Column('date_range_end', sa.String(length=80), nullable=True),
    sa.Column('coords', sa.String(length=80), nullable=True),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.Column('map_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    # ### end Alembic commands ###
